In [2]:
import torch
from torch.autograd import Variable

In [4]:
tensor = torch.FloatTensor([[3,6],[8,1]])
print(tensor)

tensor([[3., 6.],
        [8., 1.]])


In [27]:
var = Variable(tensor , requires_grad = True)
print(var)

tensor([[3., 6.],
        [8., 1.]], requires_grad=True)


In [28]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(var*var)
print(t_out)
print(v_out)

tensor(27.5000)
tensor(27.5000, grad_fn=<MeanBackward1>)


In [29]:
v_out.backward()
print(var.grad)
#v_out = 1/4*(sum)
#var = d(v_out)/d(var)
#var = 1/2*(var)
print(var.data)

tensor([[1.5000, 3.0000],
        [4.0000, 0.5000]])
tensor([[3., 6.],
        [8., 1.]])


In [31]:
print(var.data.numpy())

[[3. 6.]
 [8. 1.]]
