In [2]:
#2018/11/17
from __future__ import print_function
import torch

In [3]:
torch.ones(5, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [6]:
torch.rand(5, 3)

tensor([[0.0725, 0.9532, 0.6138],
        [0.1699, 0.9286, 0.0482],
        [0.0492, 0.0054, 0.8145],
        [0.1877, 0.2210, 0.6207],
        [0.0522, 0.5904, 0.9577]])

In [7]:
torch.randn(5, 3) 

tensor([[ 0.2656, -0.1077, -0.0677],
        [-0.8365,  0.1749, -1.8773],
        [-0.4661,  0.3240, -0.8873],
        [-1.1425, -0.0784, -1.0478],
        [-0.5885,  0.2196, -0.9473]])

In [10]:
m1 = torch.rand(5, 3)
print(m1)

tensor([[0.2172, 0.5229, 0.3053],
        [0.2275, 0.7113, 0.9941],
        [0.0057, 0.6180, 0.5205],
        [0.6205, 0.0619, 0.6747],
        [0.2950, 0.4413, 0.5719]])


In [11]:
m2 = torch.rand(5, 3)
print(m2)

tensor([[0.9168, 0.1396, 0.0950],
        [0.6773, 0.4828, 0.5665],
        [0.7474, 0.5518, 0.6551],
        [0.5985, 0.4620, 0.6618],
        [0.4335, 0.5150, 0.0854]])


In [12]:
torch.cat((m1, m2), 1)

tensor([[0.2172, 0.5229, 0.3053, 0.9168, 0.1396, 0.0950],
        [0.2275, 0.7113, 0.9941, 0.6773, 0.4828, 0.5665],
        [0.0057, 0.6180, 0.5205, 0.7474, 0.5518, 0.6551],
        [0.6205, 0.0619, 0.6747, 0.5985, 0.4620, 0.6618],
        [0.2950, 0.4413, 0.5719, 0.4335, 0.5150, 0.0854]])

In [15]:
torch.cat((m1, m2), 0)

tensor([[0.2172, 0.5229, 0.3053],
        [0.2275, 0.7113, 0.9941],
        [0.0057, 0.6180, 0.5205],
        [0.6205, 0.0619, 0.6747],
        [0.2950, 0.4413, 0.5719],
        [0.9168, 0.1396, 0.0950],
        [0.6773, 0.4828, 0.5665],
        [0.7474, 0.5518, 0.6551],
        [0.5985, 0.4620, 0.6618],
        [0.4335, 0.5150, 0.0854]])

In [16]:
m1.squeeze(1)

tensor([[0.2172, 0.5229, 0.3053],
        [0.2275, 0.7113, 0.9941],
        [0.0057, 0.6180, 0.5205],
        [0.6205, 0.0619, 0.6747],
        [0.2950, 0.4413, 0.5719]])

In [20]:
from torch.autograd import Variable
m3 = torch.ones(5, 3)
m4 = torch.ones(5, 3)
a = Variable(m3)
b = Variable(m4)
c = a + b
print(c.data)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [23]:
K = torch.linspace(start=-10, end=10, steps=5)
print(K)

tensor([-10.,  -5.,   0.,   5.,  10.])


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [53]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [54]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [55]:
z = y * y * 3
out = z.mean()

print(z, out)
out.backward()
print(x.grad)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [38]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [50]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 0.0373,  0.3233, -0.4006], requires_grad=True)
tensor([  76.3609,  662.1033, -820.3989], grad_fn=<MulBackward0>)


In [52]:
torch.Tensor(5,4)

tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00, -4.6566e-10],
        [ 8.4078e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -4.6566e-10,  1.8754e+28,  2.0592e+23],
        [ 2.0776e+20,  1.0300e-11,  1.0860e-05,  6.8249e-07],
        [ 2.6702e+23,  2.5203e-09,  1.6839e+22,  8.4490e+20]])