In [5]:
#2018/11/17
from __future__ import print_function
import torch

In [6]:
torch.ones(5, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.zeros(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [9]:
torch.rand(5, 3)

tensor([[0.2253, 0.3440, 0.4183],
        [0.5027, 0.3970, 0.4702],
        [0.8912, 0.7083, 0.8948],
        [0.7063, 0.6276, 0.1726],
        [0.2745, 0.1631, 0.0791]])

In [10]:
torch.randn(5, 3) 

tensor([[ 1.0354,  1.0499, -0.4214],
        [ 0.6254, -1.0157,  1.4421],
        [-1.9355,  0.8502, -0.8485],
        [ 1.2916,  0.2403, -0.2136],
        [-2.9802,  1.2382,  0.9236]])

In [11]:
m1 = torch.rand(5, 3)
print(m1)

tensor([[0.3312, 0.6667, 0.1627],
        [0.0589, 0.5340, 0.0216],
        [0.1513, 0.3242, 0.9208],
        [0.3166, 0.3065, 0.5119],
        [0.8300, 0.4016, 0.3988]])


In [12]:
m2 = torch.rand(5, 3)
print(m2)

tensor([[0.7566, 0.4842, 0.5758],
        [0.6494, 0.9194, 0.1246],
        [0.3260, 0.5329, 0.1196],
        [0.7592, 0.0094, 0.2140],
        [0.3467, 0.0824, 0.8087]])


In [13]:
torch.cat((m1, m2), 1)

tensor([[0.3312, 0.6667, 0.1627, 0.7566, 0.4842, 0.5758],
        [0.0589, 0.5340, 0.0216, 0.6494, 0.9194, 0.1246],
        [0.1513, 0.3242, 0.9208, 0.3260, 0.5329, 0.1196],
        [0.3166, 0.3065, 0.5119, 0.7592, 0.0094, 0.2140],
        [0.8300, 0.4016, 0.3988, 0.3467, 0.0824, 0.8087]])

In [14]:
torch.cat((m1, m2), 0)

tensor([[0.3312, 0.6667, 0.1627],
        [0.0589, 0.5340, 0.0216],
        [0.1513, 0.3242, 0.9208],
        [0.3166, 0.3065, 0.5119],
        [0.8300, 0.4016, 0.3988],
        [0.7566, 0.4842, 0.5758],
        [0.6494, 0.9194, 0.1246],
        [0.3260, 0.5329, 0.1196],
        [0.7592, 0.0094, 0.2140],
        [0.3467, 0.0824, 0.8087]])

In [15]:
m1.squeeze(1)

tensor([[0.3312, 0.6667, 0.1627],
        [0.0589, 0.5340, 0.0216],
        [0.1513, 0.3242, 0.9208],
        [0.3166, 0.3065, 0.5119],
        [0.8300, 0.4016, 0.3988]])

In [16]:
from torch.autograd import Variable
m3 = torch.ones(5, 3)
m4 = torch.ones(5, 3)
a = Variable(m3)
b = Variable(m4)
c = a + b
print(c.data)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [17]:
K = torch.linspace(start=-10, end=10, steps=5)
print(K)

tensor([-10.,  -5.,   0.,   5.,  10.])


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [20]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [21]:
z = y * y * 3
out = z.mean()

print(z, out)
out.backward()
print(x.grad)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [22]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [23]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1.3300,  0.4470,  1.8939], requires_grad=True)
tensor([-680.9706,  228.8888,  969.6980], grad_fn=<MulBackward>)


In [24]:
torch.Tensor(5,4)

tensor([[1.7177e-37, 0.0000e+00, 6.0256e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 9.5680e+20],
        [7.2065e+31, 2.6301e+20, 1.4601e-19, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 4.5580e-41,        nan, 2.6625e-44]])