In [2]:
import torch
import numpy as np

In [7]:
x = np.arange(6).reshape((3,2))
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [9]:
y = torch.from_numpy(x)
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [10]:
z = y.numpy()
print(z)

[[0 1]
 [2 3]
 [4 5]]


In [11]:
data = [-1,0,1,2,4,-6]
print(data)

[-1, 0, 1, 2, 4, -6]


In [12]:
tensor = torch.FloatTensor(data)
print(tensor)

tensor([-1.,  0.,  1.,  2.,  4., -6.])


In [13]:
print(torch.abs(tensor))

tensor([1., 0., 1., 2., 4., 6.])


In [18]:
tensor = torch.FloatTensor(data)
print(torch.sin(tensor))

tensor([-0.8415,  0.0000,  0.8415,  0.9093, -0.7568,  0.2794])


In [19]:
print(torch.cos(torch.abs(tensor)))

tensor([ 0.5403,  1.0000,  0.5403, -0.4161, -0.6536,  0.9602])


In [20]:
print(torch.mean(tensor))

tensor(0.)


In [22]:
data2 = [[2,3],[5,6]]
print(data2)

[[2, 3], [5, 6]]


In [25]:
tensor2 = torch.FloatTensor(data2)
print(torch.mm(tensor2,tensor2)) #matrix multiplication

tensor([[19., 24.],
        [40., 51.]])
